sudo: required

services:
- docker

language: bash

script:
  - docker build -t nventiveux/ttrss:latest -f Dockerfile .
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - curl -SLO https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz
  - tar zxvf qemu-arm-static.tar.gz
  - docker build -t nventiveux/ttrss:latest-arm32v6 -f Dockerfile.arm32v6 .
  - docker images

branches:
  only:
    - master
