version: "3.1"

services:

  database:
    image: postgres:10.1
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ttrss
      POSTGRES_PASSWORD: ttrss

  ttrss:
    build:
      context: .
      dockerfile: Dockerfile.amd64
    environment:
      TTRSS_CONF_SELF_URL_PATH: "http://127.0.0.1:8000/"
    volumes:
      - ttrss_cache:/srv/ttrss/cache
      - ttrss_feed_icons:/srv/ttrss/feed-icons
    ports:
      - 8000:80

volumes:

  pg_data:
  ttrss_cache:
  ttrss_feed_icons:
