name: "Auto-update"

on:
  schedule:
    - cron: '0 8 * * 6'

jobs:
  auto_update:
    name: "Auto-update"
    runs-on: "ubuntu-20.04"

    steps:
      - name: "Checkout project sources"
        uses: "actions/checkout@v2"
        with:
          ref: "${{ github.head_ref }}"
          path: "src"

      - name: "Checkout TT-RSS sources"
        run: |
          set -e
          git clone --depth=1 https://git.tt-rss.org/fox/tt-rss.git ttrss

      - name: "Fetch latest TT-RSS commit"
        id: "ttrss_fetch"
        run: |
          set -e
          commit_sha="$(cd ttrss && git rev-parse --short=7 HEAD)"
          echo "::set-output name=commit_sha::${commit_sha}"
          echo "Set pipeline variable: commit_sha=${commit_sha}"

      - name: "Update version"
        run: |
          set -e
          sed -i -r \
            -e "s#^ARG TTRSS_COMMIT=\".*\"#ARG TTRSS_COMMIT=\"${{ steps.ttrss_fetch.outputs.commit_sha }}\"#g" \
            src/Dockerfile

      - name: "Commits"
        uses: "stefanzweifel/git-auto-commit-action@v4"
        with:
          repository: "src"
          commit_message: "feat(ttrss): bump ttrss version to commit ${{ steps.ttrss_fetch.outputs.commit_sha }}"
